
language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'

before_script:
    - composer self-update
    - composer update --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover